name: arabic_lexicons
publish_to: none
description: "Arabic Lexicons"
version: 3.4.0+304000

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.4.0+2
  path: ^1.9.1
  flutter_html: ^3.0.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  crypto: ^3.0.7
  wakelock_plus: ^1.4.0
  file_picker: ^12.0.0-beta.5
  scroll_to_index: ^3.0.1
  html: ^0.15.6
  share_plus: ^13.1.0
  archive: ^4.0.9
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/data/ar_en/dictprefixes
    - assets/data/ar_en/dictstems
    - assets/data/ar_en/dictsuffixes
    - assets/data/ar_en/tableab
    - assets/data/ar_en/tableac
    - assets/data/ar_en/tablebc

    - assets/data/db/db.sqlite
    # icon
    # - assets/icons/icon.png

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/amiri/Amiri-Regular.ttf
        - asset: assets/fonts/amiri/Amiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/amiri/Amiri-Italic.ttf
          style: italic
        - asset: assets/fonts/amiri/Amiri-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Kitab
      fonts:
        - asset: assets/fonts/kitab/Kitab-Regular.ttf
        - asset: assets/fonts/kitab/Kitab-Bold.ttf
          weight: 700
    # - family: Uthman
    #   fonts:
    #     - asset: assets/fonts/uthman/uthman.ttf
    - family: Playpen
      fonts:
        - asset: assets/fonts/PlaypenSansArabic/PlaypenSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlaypenSansArabic/PlaypenSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlaypenSansArabic/PlaypenSansArabic-Bold.ttf
          weight: 700
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/noto-sans-arabic/NotoSansArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/noto-sans-arabic/NotoSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/noto-sans-arabic/NotoSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/noto-sans-arabic/NotoSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/noto-sans-arabic/NotoSansArabic-Bold.ttf
          weight: 700

    # - family: Rubik
    #   fonts:
    #     - asset: assets/fonts/rubik/Rubik-Regular.ttf
    #       weight: 400
    #     - asset: assets/fonts/rubik/Rubik-Medium.ttf
    #       weight: 500
    #     - asset: assets/fonts/rubik/Rubik-SemiBold.ttf
    #       weight: 600
    #     - asset: assets/fonts/rubik/Rubik-Bold.ttf
    #       weight: 700
    # - family: Tajawal
    #   fonts:
    #     - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
    #       weight: 400
    #     - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
    #       weight: 500
    #     - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
    #       weight: 700
    #     - asset: assets/fonts/tajawal/Tajawal-ExtraBold.ttf
    #       weight: 800
